/**
 * Prints the DUST public key the WALLET SDK derives from a seed — the ground truth FR-031 asks
 * this project's own derivation to be proved against (plan D3.2).
 *
 * Runs INSIDE the sibling SDK image (`midnight-1-offers/shielded-night-deploy:local`), which
 * carries the pinned Midnight 1.0.0 wallet SDK. Mount this directory at `/app/live` and run
 * `bun run live/dust-public-key.ts`. Nothing is added to UmbraDB's dependencies; the method is the
 * one `test/shielded-monitor/fixtures/wallet-sdk-hd-vectors.json` already used for the shielded
 * role.
 *
 * With no `SEED` it prints the three seed RECIPES that fixture uses, so the committed DUST vectors
 * can be regenerated by anyone with the image, without a seed ever being written down. With a
 * `SEED` (64 hex) it prints that wallet's DUST public key — a public value, and the identity the
 * client sends the node (Q-1) — and nothing else: the seed itself is never echoed.
 *
 *   docker run --rm --entrypoint sh -v <this dir>:/app/live:ro \
 *     midnight-1-offers/shielded-night-deploy:local -c 'cd /app && bun run live/dust-public-key.ts'
 */
import * as ledger from '@midnight-ntwrk/ledger-v8';
import { HDWallet, Roles } from '@midnightntwrk/wallet-sdk';
import { Buffer } from 'buffer';

const RECIPES: Record<string, () => Buffer> = {
  'zeros-with-last-byte-1': () => {
    const seed = Buffer.alloc(32);
    seed[31] = 1;
    return seed;
  },
  'ascending-0-to-31': () => Buffer.from(Array.from({ length: 32 }, (_, i) => i)),
  'repeated-deadbeef': () => Buffer.from('deadbeef'.repeat(8), 'hex'),
};

function dustPublicKey(seed: Buffer): { publicKey: string } {
  const hd = HDWallet.fromSeed(seed);
  if (hd.type !== 'seedOk') throw new Error('HDWallet.fromSeed failed');
  const derived = hd.hdWallet.selectAccount(0).selectRoles([Roles.Dust]).deriveKeysAt(0);
  if (derived.type !== 'keysDerived') throw new Error('deriveKeysAt failed');
  const roleSeed = derived.keys[Roles.Dust] as Uint8Array;
  const sk = ledger.DustSecretKey.fromSeed(roleSeed);
  const publicKey = (sk.publicKey as bigint).toString(10);
  // The role seed IS secret material; it is used and dropped, never printed.
  sk.clear?.();
  hd.hdWallet.clear();
  return { publicKey };
}

const explicit = process.env.SEED?.trim();
if (explicit !== undefined && explicit !== '') {
  if (!/^[0-9a-fA-F]{64}$/.test(explicit)) throw new Error('SEED must be 64 hex characters');
  const { publicKey } = dustPublicKey(Buffer.from(explicit, 'hex'));
  console.log(JSON.stringify({ path: "m/44'/2400'/0'/2/0", dustPublicKey: publicKey }, null, 2));
} else {
  const vectors = Object.entries(RECIPES).map(([seedRecipe, make]) => ({
    seedRecipe,
    dustPublicKey: dustPublicKey(make()).publicKey,
  }));
  console.log(
    JSON.stringify(
      {
        source: {
          package: '@midnightntwrk/wallet-sdk-hd (via @midnightntwrk/wallet-sdk)',
          call: 'HDWallet.fromSeed(seed).selectAccount(0).selectRoles([Roles.Dust]).deriveKeysAt(0) -> DustSecretKey.fromSeed(roleSeed).publicKey',
        },
        account: 0,
        role: Roles.Dust,
        index: 0,
        path: "m/44'/2400'/0'/2/0",
        vectors,
      },
      null,
      2,
    ),
  );
}
